name: infra_pipeline

trigger: none

pool:
  name: Default

stages:

- stage: stage1
  displayName: terraform_installer
  jobs:
  - job: install
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'


- stage: stage3
  displayName: terraform_init
  jobs:
  - job: init
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Service_connection_infra'
        backendAzureRmOverrideSubscriptionID: '38840de6-dd80-4026-aeb6-0afb4905c320'
        backendAzureRmResourceGroupName: 'infra-rg'
        backendAzureRmStorageAccountName: 'infrastg1'
        backendAzureRmContainerName: 'containerinfra'
        backendAzureRmKey: 'infra-pipeline.terraform.tfstate'



- stage: stage4
  displayName: code_scan
  jobs:
  - job: tfsec
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        debug: true

- stage: stage5
  displayName: terraform_plan
  jobs:
  - job: plan
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Service_connection_infra'
        environmentAzureRmOverrideSubscriptionID: '38840de6-dd80-4026-aeb6-0afb4905c320'

- stage: stage6
  displayName: terraform_apply
  jobs:
  - job: apply
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'Service_connection_infra'
        environmentAzureRmOverrideSubscriptionID: '38840de6-dd80-4026-aeb6-0afb4905c320'